// packages/components-svelte/src/lib/base/Wrapper.svelte
<script lang="ts">
	import type { ComponentType } from "svelte";

	/**
	 * Wrapper Component
	 *
	 * @component
	 * @example
	 * <BaseWrapper></BaseWrapper>
	 */

	/** @props Wheter or not render the wrapper */
	export let wrap: boolean;
	/** @props Component or tag to render */
	export let el: ComponentType<unknown> | string = "div";
</script>

{#if wrap}
	{#if typeof el == "string"}
		<svelte:element this={el}>
			<slot />
		</svelte:element>
	{:else}
		<svelte:component this={el}>
			<slot />
		</svelte:component>
	{/if}
{:else}
	<slot />
{/if}

// packages/components-vue/src/components/base/Wrapper.vue
<template>
	<component :is="wrapper" v-if="wrap" v-slot="elSlots" v-bind="{ ...$attrs, ...$slots }">
		<slot v-bind="{ ...elSlots }"></slot>
	</component>
	<slot v-else></slot>
</template>

<script setup lang="ts">
	import type { Teleport } from "vue";

	import type { vComponent } from "../../types/plugin";

	/**
	 * Wrapper Component
	 *
	 * Conditionally wraps content
	 *
	 * @component
	 * @example
	 * <Wrapper></Wrapper>
	 */

	defineOptions({ name: "BaseWrapper", inheritAttrs: false });
	withDefaults(
		defineProps<{
			/** Wheter or not render the wrapper */
			wrap: boolean;
			/** Component or tag to render as wrapper */
			wrapper?: vComponent | typeof Teleport | string;
		}>(),
		{ wrapper: "div" }
	);
	/**
	 * TODO: improve type safety for scoped slots in wrapper
	 */
	defineSlots<{ default(v: Record<string, any>): void }>();
</script>
